### ISSUE TITLE
[Back] 이미지 DB 저장 처리 API 개발 - feature/image-store

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI#1]
### 📌 Description

DB에 이미지 저장 및 기타 정보 저장 처리를 위한 API를 개발합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 이미지 저장을 위한 DB 리서치
- TDD 방법론을 적용하여 API 개발

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 이미지 저장을 위한 DB 리서치
  - [x] S3 리서치
  - [x] MongoDB 리서치
- [x] DB 인프라 구축
- [x] API 개발
  - [x] 테스트 코드
  - [x] repository 레이어 개발
  - [x] service 레이어 개발
  - [x] controller 레이어 개발
  - [x] 통합 테스트

**Comment by robert-min** [comment]
# 이미지 저장을 위한 DB 리서치

## Amazon Simple Storage Service (S3)

- 아마존 웹 서비스(AWS)의 객체 스토리지 서비스로, 데이터를 안전하게 저장하고 검색할 수 있는 확장 가능한 스토리지 솔루션

### S3 주요 특징

1. 데이터 저장 및 관리:
- 객체 스토리지: 파일, 이미지, 비디오 등을 객체로 저장합니다.
- 버킷: 객체를 담는 컨테이너로서 S3에서 데이터를 구분하는 단위입니다.

2. 데이터의 안전성 및 내구성:
- S3는 데이터를 여러 개의 시설과 장치에 분산하여 안정성을 보장합니다.
- 내구성이 높아 데이터의 손실이 거의 없습니다.

3. 버전 관리:
- S3는 객체의 버전 관리를 지원하므로 이전 버전의 객체를 보존할 수 있습니다.

4. 액세스 제어:
- 버킷 정책과 IAM 정책을 사용하여 데이터에 대한 액세스 권한을 관리할 수 있습니다.
- 데이터를 비공개로 유지하거나, 특정 사용자 또는 그룹에 대한 읽기 또는 쓰기 권한을 부여할 수 있습니다.

### 비용

1. 저장 비용:
- 데이터의 저장량에 따라 비용이 부과됩니다.
- 저장된 데이터의 양과 선택한 스토리지 클래스에 따라 비용이 달라집니다.

2. 데이터 전송 비용:
- 데이터의 전송과 다운로드에 대해 비용이 발생합니다.
- 데이터가 AWS S3로 업로드되거나 AWS S3에서 다운로드되는 양에 따라 비용이 책정됩니다.

3. 리퀘스트 비용:
- S3에 대한 각각의 API 요청(예: 객체 읽기, 쓰기, 삭제)에 대한 비용이 있습니다.

4. 버전 관리 및 수명 주기 비용:
- 버전 관리를 사용하거나 수명 주기 정책을 설정한 경우에 추가 비용이 발생할 수 있습니다.

5. 암호화 비용:
- S3 객체에 대한 서버 측 암호화를 사용하는 경우 암호화에 대한 비용이 추가될 수 있습니다.

## Azure CosmosDB - MongoDB

- Microsoft Azure에서 제공하는 다중 모델 데이터베이스 서비스로서, NoSQL 데이터베이스 중 하나로 MongoDB API를 지원
- MongoDB API를 사용하면 기존 MongoDB 응용 프로그램을 Cosmos DB로 마이그레이션하거나 새로운 응용 프로그램을 개발

### CosmosDB - MongoDB 주요 특징

1. 다중 모델 데이터베이스:
- Cosmos DB는 다중 모델 데이터베이스로서, MongoDB API 외에도 SQL, Gremlin, Cassandra, Table API를 지원합니다.

2. 글로벌 분산:
- Cosmos DB는 데이터를 여러 지역에 분산하여 세계 각지에서 접근할 수 있도록 합니다.
- 지연 시간이 최소화되며, 사용자에게 최적의 성능을 제공합니다.

3. 자동 확장:
- Cosmos DB는 자동으로 확장되며, 데이터 양과 처리량에 따라 유연하게 조정됩니다.
- 응용 프로그램이 변동하는 수요에 따라 자동으로 조정됩니다.

4. 보안 및 권한:
- Cosmos DB는 데이터 암호화, 가용성을 위한 복제, 역할 기반의 액세스 제어 등을 통해 보안을 강화합니다.

5. 모니터링 및 진단:
- Azure Portal 및 다양한 모니터링 도구를 통해 Cosmos DB 인스턴스의 성능을 모니터링하고 진단할 수 있습니다.

### 비용 구조

1. 저장 비용:
- Cosmos DB에 저장된 데이터 양에 따라 비용이 부과됩니다.

2. 처리량 비용:
- 읽기 및 쓰기 처리량에 따라 비용이 발생합니다.
- 쓰기 처리량은 초당 쓰기 요청 수로 측정되며, 읽기 처리량은 초당 읽기 요청 수로 측정됩니다.

3. 인덱스 비용:
- Cosmos DB는 쿼리 성능을 향상시키기 위해 자동으로 인덱스를 생성하며, 이에 따라 인덱스 관리에 대한 비용이 발생할 수 있습니다.

4. 스토리지 트랜잭션 비용:
- 데이터베이스의 트랜잭션에 대한 비용이 있습니다.

5.리전 간 복제 비용:
- Cosmos DB의 데이터를 여러 지역에 복제하면 해당 리전 간 데이터 전송 비용이 발생할 수 있습니다.


## DB 결정

> - 이미지 저장 관점에서는 AWS S3가 Azure CosmosDB 보다 효율적임.
> - 하지면 현재 프로젝트의 경우 이미지만 별도로 저장하는 것이 아닌 텍스트 등의 함께 저장해야할 별도 데이터가 있기 때문에, S3외에도 추가적인 DB 사용이 필요
> - 또 CosmosDB의 경우 1년간 무료 사용량을 제공하기 때문에 비용적으로 효율적
> - 현재 프로젝트는 CosmosDB 사용

**Comment by robert-min** [comment]
## 스터디 참고 링크

[TDD방법론](https://inpa.tistory.com/entry/QA-%F0%9F%93%9A-TDD-%EB%B0%A9%EB%B2%95%EB%A1%A0-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%A3%BC%EB%8F%84-%EA%B0%9C%EB%B0%9C)

[Layered Architecture](https://velog.io/@ygreenb/Layered-Architecture)
[Layered Architecture의 장단점](https://gnuoyus.tistory.com/70)
