### ISSUE TITLE
[Back] Focus point 기능 연동 - feature/focus-point

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI#10]
### 📌 Description

백엔드 서버에 focus point 기능 연동합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- Focus point 라이브러리 연동
- DB 저장 확인
- Front 응답값 확인

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] Openai API 리서치
- [x] Focus point 라이브러리 연동
  - [x] lib/focus_point/openai 개발
  - [x] API 연동
  - [x] 테스트
- [x] Front 응답값 확인
