### ISSUE TITLE
[Back] User API 코드 리팩토링 - refactor/image-store

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI#7]
### 📌 Description

이전에 작업한 `feature/image-store` 코드의 가독성, 확장성을 고려한 코드 리팩토링 작업 수행

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- User service, repository 레이어 수정
- account 코드를 참고하여 코드 가독성에 용이한 코드 작성
- 이미지 파일 처리 수정
- test_service 코드에서 DBError 수정 -> 로컬에서 돌릴 수 있는지?
- 로그인 필수 연동
- 로깅 기능 추가

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 레이어 수정
  - [x] service 수정(init 제거)
  - [x] repository 수정(init제거)
- [x] user 폴더 이전
- [x] libs 폴더 수정
- [x] 이미지 수정
  - [x] generated_unque_id (timestamp+유저이메일 문자열 생성)
  - [x] 확장자 수정(현재 png 강제함)
- [x] 코드 수정
  - [x] email 용어 -> id로 수정
  - [x] test코드 EMAIL -> id 수정, test email 이름 다르게 수정

**Comment by robert-min** [comment]
## 이미지 저장 가이드

### 저장이 필요한 데이터

유저정보
- 사용자 정보(user_account)
  - email
  - password
  - name
  - gender
  - age
  - generated_account
  - status
- 사용자 활동 정보(user_active)
  - email
  - generated_id

이미지
- 사용자로부터 받은 이미지(Local, MongoDB, Redis)
  - Crop 이미지
  - Super Resolution 이미지
- 생성한 이미지


> 데모 기준 사용자로부터 받은 이미지 그래도 사용, 데모 이후 Super Resolution 이미지 저장

텍스트(MongoDB, Redis)
- 생성한 텍스트 설명
- Focus Point 좌표값

영상(Local, S3)
- OpenCV로 만든 대기 화면
- Image to Video(애니메이션?)

음성(Local, S3)
- 생성한 이미지 설명 음성 TTS

### 저장소 별 데이터 관리

#### Local
- 경로 : userdata/{유저이메일}
- 저장 시점 : 각 파일이 생성될 때 바로 로컬에 저장
- 저장할 데이터
  - 유저 입력 이미지(origin_img.{확장자})
  - 생성 이미지(generate_img.{확장자})
  - 생성 영상(generate_video.{확장자})
  - 생성 음성(generate_voide.{확장자})
- 삭제 시점 : 폴더명 기준 1시간 이후 삭제


#### PostgreSQL
- 경로 : art / user_account
- 저장 시점 : 회원가입
- 저장할 데이터
  - email
  - password
  - name
  - gender
  - age
  - generated_account
  - status

- 경로 : art / user_active
- 저장 시점 : MongoDB user_generated document에 값이 입력되었을 때,
  - email
  - generated_id


#### MongoDB
- 경로 : art / user_generated
- 저장 시점 : 아래 데이터가 다 생성되었을 때 저장 요청
- 저장할 데이터
  - _id : 생성시간(timestamp)+유저아이디(email)
  - generated_text: 생성한 텍스트
  - coordinate_value: 생성된 좌표값 {좌표명: {x, y}...}
  - origin_img: 원본 이미지
  - generated_img: 생성한 이미지
 
- 경로 : art / user_feedback
- 저장 시점 : 유저 피드백이 완료되었을 때
- 저장할 데이터
  - _id : user_active.generated_id와 동일
  - feedback: {문항 : 응답, ...}

#### Object Storage(S3)
- 경로 : art / {유저이메일}
- 저장 시점 : 음성, 영상 콘텐츠를 다 전달했을 때 저장 요청
- 저장할 데이터
  - 폴더명 : user_active.generated_id와 동일 (압축해서 저장)
    - 생성 영상(generate_video.{확장자})
    - 생성 음성(generate_voide.{확장자})

#### Redis
- 경로 : user_active.generated_id와 동일 
- 저장 시점 : MongoDB user_generated document에 값이 입력되었을 때
- 저장할 데이터
  - _id : 생성시간(timestamp)+유저아이디(email)
  - generated_text: 생성한 텍스트
  - coordinate_value: 생성된 좌표값 {좌표명: {x, y}...}
  - origin_img: 원본 이미지
  - generated_img: 생성한 이미지
