### ISSUE TITLE
[Back] 로그인 - 이미지 저장 연동 및 로깅 기능 개발 - feature/connect-logging

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI#9]
### 📌 Description

이미지 저장 API를 로그인해서 이용할 수 있도록 코드 연동 및 API 로깅 기능 추가

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 이미지 저장 API와 로그인을 연동
- Opensearch를 활용한 로깅 기능 추가

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 이미지 저장 API 로그인 연동
- [x] 로깅 기능 추가
  - [x] Opensearch 인프라 확인 및 구축
  - [x] 로깅 기능 추가
- [x] user_active 컬럼 추가 작업
  - [x] DB 테이블 추가
  - [x] 이미지 처리 후 id 정보 저장 추가

**Comment by robert-min** [comment]
![image](https://github.com/FLYAI4/ArtAPI-FastAPI/assets/91866763/1221d558-da99-4668-9be6-be64d433d6d8)

**Comment by robert-min** [comment]
### ArtAPI-FastAPI-DDD 확인

![image](https://github.com/FLYAI4/ArtAPI-FastAPI/assets/91866763/0a6ef200-5d27-4142-b264-c3753bab159d)
